spring:
  application:
    name: gw

server:
  port: 1110
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
      preferIpAddress: true
zuul:
  routes:
    inventory-service: /inventory/**
  ignored-services: '*'